Metrics/BlockLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
